### ISSUE TITLE
Empty audio file

### ISSUE THREAD

**Issue by pajeronda** [Nortonko/rhasspy-MSAzure#1]
Hi Nortonko
I'm installing your script and so far I've managed to get the audio files in the cache, in wav format, but they don't play. If I open them with another media player it tells me, they are empty.
My rhasspy 2.5.11 is a home assistant addon and to reach it I configured the script paths, I think correctly, because it created the folder and wav files (but empty). Do you have any ideas on what could be causing this problem? If I make a mistake in some parameter (API type or other) are the files created or does the script crash first? I didn't change the OutputFormat, just the required data.
Thank you

**Comment by pajeronda** [comment]
> [ERROR:2024-02-13 11:28:24,987] rhasspyserver_hermes: file does not start with RIFF id
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1699, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1685, in speak
    say_chars_per_second=say_chars_per_second,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 626, in speak_sentence
    raise TtsException(say_response.error)
rhasspyserver_hermes.TtsException: file does not start with RIFF id
[ERROR:2024-02-13 11:28:24,986] rhasspyserver_hermes: TtsError(error='file does not start with RIFF id', site_id='rhasspy', context='515b6f71-14fd-49f1-94f2-5ec3f1e09258', session_id='')
[DEBUG:2024-02-13 11:28:24,985] rhasspyserver_hermes: Handling TtsError (topic=hermes/error/tts, id=433dcff9-3c5e-4d94-8c17-f9b6e5a0d9e3)
[DEBUG:2024-02-13 11:28:24,981] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/rhasspy/playBytes/515b6f71-14fd-49f1-94f2-5ec3f1e09258, id=433dcff9-3c5e-4d94-8c17-f9b6e5a0d9e3)
[DEBUG:2024-02-13 11:28:24,833] rhasspyserver_hermes: Publishing 129 bytes(s) to hermes/tts/say
[DEBUG:2024-02-13 11:28:24,833] rhasspyserver_hermes: -> TtsSay(text='ciao', site_id='rhasspy', lang=None, id='515b6f71-14fd-49f1-94f2-5ec3f1e09258', session_id='', volume=1.0)
[DEBUG:2024-02-13 11:28:24,832] rhasspyserver_hermes: TTS timeout will be 30 second(s)

**Comment by Nortonko** [comment]
Hi,
please check you API key and other parameters _(tokenurl, voice, lang, gender, host)_  if it setting corect. Also try running the script directly from the command line like:
`./rhasspy_azure_says.sh "how are you"` and check the output. You should get "_unintelligible_" text on the screen, and it should also create an audio file in a preset cache directory

**Comment by pajeronda** [comment]
Thanks, after your reply I put the data back into a new original file and everything worked properly. Thank you!
